[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "sanssouci"
version = "0.1.5"
dependencies = [
    "joblib       >= 1.2.0, < 2",
    "numpy        >= 1.25,  < 3",
    "scikit-learn >= 1.5,   < 1.9",
    "scipy        >= 1.9.2, < 2",
]
authors = [
    {name = "Alexandre Blain"},
    {name = "Nicolas Enjalbert Courrech"},
    {name = "Pierre Neuvial", email = "pierre.neuvial@math.univ-toulouse.fr"},
    {name = "Nils Peyrouset"},
    {name = "Laurent Risser", email = "laurent.risser@math.univ-toulouse.fr"},
    {name = "Bertrand Thirion", email = "bertrand.thirion@inria.fr"},
]
maintainers = [
    {name = "Pierre Neuvial", email = "pierre.neuvial@math.univ-toulouse.fr"}
]
description = "Post hoc inference via multiple testing"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
license = {text = "GNU General Public License v3 (GPLv3)"}
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/sanssouci-org/sanssouci.python"
Issues = "https://github.com/sanssouci-org/sanssouci.python/issues"